# Generated by Django 3.2.7 on 2021-11-16 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mainService', models.CharField(max_length=100, verbose_name='Main')),
                ('my_field', multiselectfield.db.fields.MultiSelectField(choices=[('ODOO DEVELOPMENT', 'ODOO DEVELOPMENT'), ('CODE UPGRADING', 'CODE UPGRADING'), ('DATABASE MIGRATION', 'DATABASE MIGRATION'), ('LINUX ADMINISTRATION', 'LINUX ADMINISTRATION')], max_length=71)),
                ('SpecialOrder', models.CharField(blank=True, default='None', max_length=100, null=True, verbose_name='Special')),
            ],
        ),
        migrations.CreateModel(
            name='Contact1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone number')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='company')),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.TextField(blank=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueTitle', models.CharField(max_length=100, verbose_name='issue Title')),
                ('issueContent', models.TextField(verbose_name='issue content')),
                ('snapShot', models.ImageField(blank=True, default='default.png', null=True, upload_to='photos1/%y/%m/%d')),
                ('status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Done', 'Done'), ('Waiting', 'Waiting reply')], default='Open', max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Time added')),
                ('updates', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Time added')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.ticket')),
            ],
        ),
    ]
