# Generated by Django 3.2.7 on 2021-11-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_reply',
            name='comment',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
