# Generated by Django 3.2.7 on 2021-11-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_ticket_reply_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket_reply',
            name='comment',
        ),
        migrations.AddField(
            model_name='ticket',
            name='comment',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
