# Generated by Django 3.2.7 on 2021-11-19 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20211116_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='datebaseTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.CharField(max_length=100, verbose_name='Database Name')),
            ],
            options={
                'verbose_name': 'datebaseTicket',
                'verbose_name_plural': 'datebaseTickets',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='dbRelated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.datebasetickets'),
        ),
    ]
