# Generated by Django 3.2.7 on 2021-11-19 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20211119_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_reply',
            name='dbRelated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.datebasetickets'),
        ),
    ]
