# Generated by Django 3.2.7 on 2021-11-19 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0005_ticket_reply_dbrelated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket_reply',
            name='dbRelated',
        ),
        migrations.AddField(
            model_name='datebasetickets',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
