# Generated by Django 3.2.7 on 2021-12-02 08:48

import contact.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20211119_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datebasetickets',
            name='db',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Database Name'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dbRelated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.datebasetickets', verbose_name='Database'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='snapShot',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=contact.models.image_upload_handler),
        ),
    ]
