# Generated by Django 3.2.7 on 2021-12-28 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_auto_20211213_2157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auto_Reply',
        ),
    ]
