# Generated by Django 3.2.7 on 2021-12-28 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211228_2155'),
        ('contact', '0013_ticket_auto_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='auto_reply',
        ),
        migrations.CreateModel(
            name='autoReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aiReply', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.auto_reply')),
                ('ticket', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contact.ticket')),
            ],
        ),
    ]
