# Generated by Django 3.2.7 on 2021-12-28 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211228_2155'),
        ('contact', '0014_auto_20211229_0052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='autoReply',
            new_name='Ai_Reply',
        ),
    ]
