# Generated by Django 3.2.7 on 2022-04-02 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0015_rename_autoreply_ai_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='link',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='solution',
        ),
    ]
