# Generated by Django 3.2.7 on 2021-09-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=50, verbose_name='CompanyName')),
                ('companyLogo', models.ImageField(default='https://www.odoo.com/web/image/res.users/1072846/image_1024?unique=3f33558', upload_to='photos/%y/%m/%d')),
                ('companyAdress', models.TextField(verbose_name='Adress')),
                ('companyUrl', models.CharField(max_length=200, verbose_name='URL')),
                ('comapyEmail', models.CharField(max_length=20, verbose_name='Email')),
                ('comapnyCountry', models.CharField(max_length=50, verbose_name='Country')),
                ('category', models.CharField(blank=True, choices=[('DM', 'Database Migration'), ('OD', 'Odoo Development')], max_length=50, null=True)),
            ],
        ),
    ]
