# Generated by Django 3.2.7 on 2021-09-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projomania_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone number')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='company')),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.TextField(blank=True)),
                ('data', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='companies',
            name='category',
            field=models.CharField(blank=True, choices=[('Database Migration', 'Database Migration'), ('Odoo Development', 'Odoo Development')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='comapnyCountry',
            field=models.CharField(choices=[('usa', 'usa'), ('belgim', 'belgim')], max_length=50, verbose_name='Country'),
        ),
    ]
