# Generated by Django 3.2.7 on 2021-10-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projomania_pages', '0003_alter_contact1_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='id',
        ),
        migrations.AddField(
            model_name='companies',
            name='companytest',
            field=models.CharField(default='null', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='companies',
            name='comapnyCountry',
            field=models.CharField(choices=[('usa', 'usa'), ('belgim', 'belgim'), ('Austria', 'Austria')], max_length=50, verbose_name='Country'),
        ),
    ]
