# Generated by Django 3.2.7 on 2021-10-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projomania_pages', '0004_auto_20211002_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='companytest',
        ),
        migrations.AddField(
            model_name='companies',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
