# Generated by Django 3.2.7 on 2021-10-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projomania_pages', '0005_auto_20211002_1310'),
    ]

    operations = [
        migrations.AddField(

            model_name='companies',
            name='slug',
            field=models.SlugField(default='name', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
