# Generated by Django 3.2.7 on 2021-10-10 11:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projomania_pages', '0006_companies_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mainService', models.CharField(max_length=100, verbose_name='Main')),
                ('my_field', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3'), ('item_key4', 'Item title 1.4'), ('item_key5', 'Item title 1.5')], max_length=49, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='companies',
            name='category',
            field=models.CharField(blank=True, choices=[('Database Migration', 'Database Migration'), ('Odoo Development', 'Odoo Development'), ('none', 'none'), ('---------', '---------')], default='none', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='comapnyCountry',
            field=models.CharField(blank=True, choices=[('usa', 'usa'), ('belgim', 'belgim'), ('Austria', 'Austria'), ('none', 'none')], default='none', max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='comapyEmail',
            field=models.CharField(blank=True, max_length=20, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='companyAdress',
            field=models.TextField(blank=True, verbose_name='Adress'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='companyUrl',
            field=models.CharField(blank=True, max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='URL IN SITE'),
        ),
    ]
