# Generated by Django 3.2.7 on 2021-10-10 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projomania_pages', '0008_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
