# Generated by Django 3.2.7 on 2021-10-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projomania_pages', '0009_delete_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='Booking',
        ),
    ]
