# Generated by Django 3.2.7 on 2021-10-18 03:26

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projomania_pages', '0010_rename_mymodel_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='SpecialOrder',
            field=models.CharField(default='test', max_length=100, verbose_name='Special'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='my_field',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ODOO DEVELOPMENT', 'ODOO DEVELOPMENT'), ('CODE UPGRADING', 'CODE UPGRADING'), ('DATABASE MIGRATION', 'DATABASE MIGRATION'), ('LINUX ADMINISTRATION', 'LINUX ADMINISTRATION')], max_length=71, null=True),
        ),
    ]
