# Generated by Django 3.2.7 on 2021-10-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projomania_pages', '0012_auto_20211019_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='companyLogo',
            field=models.ImageField(default='projomania_pages\\static\\images\\default.png', upload_to='photos/%y/%m/%d'),
        ),
    ]
