# Generated by Django 3.2.7 on 2021-10-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projomania_pages', '0013_alter_companies_companylogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='companyLogo',
            field=models.ImageField(default='default.png', upload_to='photos/%y/%m/%d'),
        ),
    ]
