# Generated by Django 3.2.7 on 2021-11-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projomania_pages', '0014_alter_companies_companylogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueTitle', models.CharField(max_length=100, verbose_name='Name')),
                ('issueContent', models.TextField()),
                ('snapShot', models.ImageField(default='default.png', upload_to='snapshots/%y/%m/%d')),
            ],
        ),
    ]
