# Generated by Django 3.2.7 on 2021-11-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projomania_pages', '0015_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Done', 'Done'), ('Waiting', 'Waiting reply')], default='none', max_length=50, null=True),
        ),
    ]
