# Generated by Django 3.2.7 on 2021-11-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projomania_pages', '0016_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='snapShot',
            field=models.ImageField(default='default.png', upload_to='photos/%y/%m/%d'),
        ),
    ]
