# Generated by Django 3.2.7 on 2021-11-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projomania_pages', '0019_auto_20211111_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updates',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
