# Generated by Django 3.2.7 on 2021-11-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projomania_pages', '0023_auto_20211114_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='issueContent',
            field=models.TextField(verbose_name='issue content'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='issueTitle',
            field=models.CharField(max_length=100, verbose_name='issue Title'),
        ),
    ]
