# Generated by Django 3.2.7 on 2021-11-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projomania_pages', '0024_auto_20211114_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Done', 'Done'), ('Waiting', 'Waiting reply')], default='Open', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Time added'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updates',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated'),
        ),
    ]
