# Generated by Django 3.2.7 on 2021-11-16 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projomania_pages', '0025_auto_20211116_0127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Contact1',
        ),
        migrations.RemoveField(
            model_name='ticket_reply',
            name='author',
        ),
        migrations.RemoveField(
            model_name='ticket_reply',
            name='ticket',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='Ticket_reply',
        ),
    ]
