# Generated by Django 3.2.7 on 2021-12-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projomania_pages', '0027_alter_companies_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='id',
        ),
        migrations.AlterField(
            model_name='companies',
            name='slug',
            field=models.SlugField(blank=True, default=1, max_length=255, primary_key=True, serialize=False, verbose_name='URL IN SITE'),
            preserve_default=False,
        ),
    ]
