# Generated by Django 3.2.7 on 2021-12-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projomania_pages', '0028_auto_20211213_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companies',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='URL IN SITE'),
        ),
    ]
