# Generated by Django 3.2.7 on 2021-12-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Time added'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated'),
        ),
    ]
