# Generated by Django 3.2.7 on 2021-12-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211214_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto_Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                
            ],
            options={
                'verbose_name': 'Error',
                'verbose_name_plural': 'Errors',
            },
        ),
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['-added'], 'verbose_name': 'Blogs', 'verbose_name_plural': 'Blogs'},
        ),
    ]
