# Generated by Django 3.2.7 on 2022-04-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211228_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto_reply',
            name='error',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auto_reply',
            name='link',
            field=models.URLField(default='b'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auto_reply',
            name='solution',
            field=models.TextField(default='c'),
            preserve_default=False,
        ),
    ]
