# Generated by Django 3.2.7 on 2022-04-02 19:50

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220402_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto_reply',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.image_upload_handler),
        ),
    ]
