# Generated by Django 3.2.7 on 2021-12-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='URL IN SITE')),
                ('companyName', models.CharField(max_length=50, verbose_name='CompanyName')),
                ('companyLogo', models.ImageField(default='default.png', upload_to='photos/%y/%m/%d')),
                ('companyAdress', models.TextField(blank=True, verbose_name='Adress')),
                ('companyUrl', models.CharField(blank=True, max_length=200, verbose_name='URL')),
                ('comapyEmail', models.CharField(blank=True, max_length=20, verbose_name='Email')),
                ('comapnyCountry', models.CharField(blank=True, choices=[('usa', 'usa'), ('belgim', 'belgim'), ('Austria', 'Austria'), ('none', 'none')], default='none', max_length=50, verbose_name='Country')),
                ('category', models.CharField(blank=True, choices=[('Database Migration', 'Database Migration'), ('Odoo Development', 'Odoo Development'), ('none', 'none'), ('---------', '---------')], default='none', max_length=50, null=True)),
            ],
        ),
    ]
