# Generated by Django 3.2.7 on 2021-12-28 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={'verbose_name': 'Companie', 'verbose_name_plural': 'Companies'},
        ),
    ]
